### ISSUE TITLE
[BUG/Question] auth_time is parsed as a string, should be int

### ISSUE THREAD

**Issue by roman-van-der-krogt** [Intility/fastapi-azure-auth#166]
**Describe the bug**

We are using Azure B2C with tokens including the `auth_time` field.  Validation of such tokens fails with

```
Unable to process jwt token. Uncaught error: 1 validation error for User
auth_time
  Input should be a valid string [type=string_type, input_value=1698160644, input_type=int]
```

The expected input type is incorrect, and should be changed to an int [here](https://github.com/Intility/fastapi-azure-auth/blob/c65a4876189fef8f9bfef18f499a149b25c49c82/fastapi_azure_auth/user.py#L94). From the Open Id specs (https://openid.net/specs/openid-connect-core-1_0.html):

```
auth_time
Time when the End-User authentication occurred. Its value is a JSON number representing the number of seconds 
from 1970-01-01T0:0:0Z as measured in UTC until the date/time. 
```

**To Reproduce**
Try to validate a token with the `auth_time` field present

**Stack trace**

```
auth_time
  Input should be a valid string [type=string_type, input_value=1698160644, input_type=int]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
Traceback (most recent call last):
  File "<snip>/lib/python3.10/site-packages/fastapi_azure_auth/auth.py", line 208, in __call__
    user: User = User(
  File "<snip>/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for User
auth_time
  Input should be a valid string [type=string_type, input_value=1698160644, input_type=int]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
```

**Your configuration**
fastapi-azure-auth 4.2.1

**Comment by JonasKs** [comment]
Hi, thanks for the report! 
PR welcome 😊

**Comment by roman-van-der-krogt** [comment]
PR sent 😄
