### ISSUE TITLE
Auth with React

### ISSUE THREAD

**Issue by ocni-dtu** [Intility/fastapi-azure-auth#73]
**Describe the bug**

Hey all,
Thanks for a great library!
I have with success implemented the auth workflow with FastAPI and OpenAPI following your [documentation](https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup)
I have a React frontend that needs to talk to the FastAPI backend and I have trouble getting it to work. I use the `"@azure/msal-browser"` package to get the access token in React, but when I send it in the header to FastAPI I get the following error:
```
Traceback (most recent call last):
   File "/app/.local/lib/python3.9/site-packages/fastapi_azure_auth/auth.py", line 183, in __call__
     token = jwt.decode(
   File "/app/.local/lib/python3.9/site-packages/jose/jwt.py", line 144, in decode
     raise JWTError(e)
 jose.exceptions.JWTError: Signature verification failed.
 INFO:     127.0.0.1:36092 - "GET /api/project/a833b3ff30 HTTP/1.1" 401 Unauthorized
```
I have followed the same steps as for OpenAPI to setup my React SPA in Azure.

**To Reproduce**
1. Go to React UI
2. Login to Azure
3. Catch the token from the callback
4. Set the token in the header
5. Call FastAPI

**Stack trace**
```
[backend] INFO:     127.0.0.1:36088 - "OPTIONS /api/project/a833b3ff30 HTTP/1.1" 200 OK
[backend] 2022-04-21 12:40:18,023 WARNING fastapi_azure_auth __call__() Malformed token received. null. Error: Error decoding token headers.
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 176, in _load
[backend]     signing_input, crypto_segment = jwt.rsplit(b".", 1)
[backend] ValueError: not enough values to unpack (expected 2, got 1)
[backend] 
[backend] During handling of the above exception, another exception occurred:
[backend] 
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jwt.py", line 183, in get_unverified_header
[backend]     headers = jws.get_unverified_headers(token)
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 109, in get_unverified_headers
[backend]     return get_unverified_header(token)
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 90, in get_unverified_header
[backend]     header, claims, signing_input, signature = _load(token)
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 180, in _load
[backend]     raise JWSError("Not enough segments")
[backend] jose.exceptions.JWSError: Not enough segments
[backend] 
[backend] During handling of the above exception, another exception occurred:
[backend] 
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/fastapi_azure_auth/auth.py", line 136, in __call__
[backend]     header: dict[str, str] = jwt.get_unverified_header(token=access_token) or {}
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jwt.py", line 185, in get_unverified_header
[backend]     raise JWTError("Error decoding token headers.")
[backend] jose.exceptions.JWTError: Error decoding token headers.
[backend] INFO:     127.0.0.1:36088 - "GET /api/project/a833b3ff30 HTTP/1.1" 401 Unauthorized
[backend] 2022-04-21 12:40:18,150 WARNING fastapi_azure_auth __call__() Invalid token. Error: Signature verification failed.
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 262, in _verify_signature
[backend]     raise JWSSignatureError()
[backend] jose.exceptions.JWSSignatureError
[backend] 
[backend] During handling of the above exception, another exception occurred:
[backend] 
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jwt.py", line 142, in decode
[backend]     payload = jws.verify(token, key, algorithms, verify=verify_signature)
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 73, in verify
[backend]     _verify_signature(signing_input, header, signature, key, algorithms)
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 264, in _verify_signature
[backend]     raise JWSError("Signature verification failed.")
[backend] jose.exceptions.JWSError: Signature verification failed.
[backend] 
[backend] During handling of the above exception, another exception occurred:
[backend] 
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/fastapi_azure_auth/auth.py", line 183, in __call__
[backend]     token = jwt.decode(
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jwt.py", line 144, in decode
[backend]     raise JWTError(e)
[backend] jose.exceptions.JWTError: Signature verification failed.
[backend] INFO:     127.0.0.1:36088 - "GET /api/project/a833b3ff30 HTTP/1.1" 401 Unauthorized
[backend] 2022-04-21 12:43:06,084 WARNING fastapi_azure_auth __call__() Malformed token received. null. Error: Error decoding token headers.
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 176, in _load
[backend]     signing_input, crypto_segment = jwt.rsplit(b".", 1)
[backend] ValueError: not enough values to unpack (expected 2, got 1)
[backend] 
[backend] During handling of the above exception, another exception occurred:
[backend] 
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jwt.py", line 183, in get_unverified_header
[backend]     headers = jws.get_unverified_headers(token)
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 109, in get_unverified_headers
[backend]     return get_unverified_header(token)
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 90, in get_unverified_header
[backend]     header, claims, signing_input, signature = _load(token)
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 180, in _load
[backend]     raise JWSError("Not enough segments")
[backend] jose.exceptions.JWSError: Not enough segments
[backend] 
[backend] During handling of the above exception, another exception occurred:
[backend] 
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/fastapi_azure_auth/auth.py", line 136, in __call__
[backend]     header: dict[str, str] = jwt.get_unverified_header(token=access_token) or {}
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jwt.py", line 185, in get_unverified_header
[backend]     raise JWTError("Error decoding token headers.")
[backend] jose.exceptions.JWTError: Error decoding token headers.
[backend] INFO:     127.0.0.1:36092 - "GET /api/project/a833b3ff30 HTTP/1.1" 401 Unauthorized
[backend] 2022-04-21 12:43:06,334 WARNING fastapi_azure_auth __call__() Invalid token. Error: Signature verification failed.
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 262, in _verify_signature
[backend]     raise JWSSignatureError()
[backend] jose.exceptions.JWSSignatureError
[backend] 
[backend] During handling of the above exception, another exception occurred:
[backend] 
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jwt.py", line 142, in decode
[backend]     payload = jws.verify(token, key, algorithms, verify=verify_signature)
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 73, in verify
[backend]     _verify_signature(signing_input, header, signature, key, algorithms)
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jws.py", line 264, in _verify_signature
[backend]     raise JWSError("Signature verification failed.")
[backend] jose.exceptions.JWSError: Signature verification failed.
[backend] 
[backend] During handling of the above exception, another exception occurred:
[backend] 
[backend] Traceback (most recent call last):
[backend]   File "/app/.local/lib/python3.9/site-packages/fastapi_azure_auth/auth.py", line 183, in __call__
[backend]     token = jwt.decode(
[backend]   File "/app/.local/lib/python3.9/site-packages/jose/jwt.py", line 144, in decode
[backend]     raise JWTError(e)
[backend] jose.exceptions.JWTError: Signature verification failed.
[backend] INFO:     127.0.0.1:36092 - "GET /api/project/a833b3ff30 HTTP/1.1" 401 Unauthorized

```

**Comment by JonasKs** [comment]
Can you de code your token at https://jwt.io and show me how it looks? If you're not comfortable posting that information online, you can send it to me at jonas.svensson@intility.no. 

Also, your react frontend is set up exactly as the OpenAPI app registration?

**Comment by ocni-dtu** [comment]
Sure here is a [link to the token](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJub25jZSI6InFsb0dGTmQxYzVwRnBQN3c5cGNydDMtUXdqRGVJamh2OF9HWHZsaWt1anMiLCJhbGciOiJSUzI1NiIsIng1dCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyIsImtpZCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xMWJlMTUzOC03OWQ4LTQ5MzktODJiOC1iNzY3ODA1ZDgyNWIvIiwiaWF0IjoxNjUwODc2MzgwLCJuYmYiOjE2NTA4NzYzODAsImV4cCI6MTY1MDg4MDcxMywiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iXSwiYWlvIjoiQVZRQXEvOFRBQUFBeWRTSEpmVEFlMjhtV3IrcklsbjJIS25aYTJiMjdZL1V5TWREaDgwMHdUOXdWM2pmbm5BcDB2aHlkbGU2d1JpbG04eXRSbWk5TU1JZWt0WVBueVBsaGRVUmE2cjFmU3BmbzF0eTlKSEdXSDg9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBfZGlzcGxheW5hbWUiOiJsY2F0b29sX1JlYWN0IiwiYXBwaWQiOiJlNmU1MWQ1OS04MzNhLTRlYzQtYjUzMy0yYmJiODg2ZjZkMzEiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IktvbmdzZ2FhcmQiLCJnaXZlbl9uYW1lIjoiQ2hyaXN0aWFuIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTk1LjkzLjE5Mi4xOTMiLCJuYW1lIjoiQ2hyaXN0aWFuIEtvbmdzZ2FhcmQiLCJvaWQiOiI2MDA2N2Q4MC0zYmQwLTQyYjctOGIxNy0yYjljMGM4YWFmZjMiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMTA4NjUyMzQ0MC0xMTg3NTQ4MzUtMTEzNjI2Mzg2MC03MzQ1MTUiLCJwbGF0ZiI6IjgiLCJwdWlkIjoiMTAwMzIwMDFEOTk0NTc5MSIsInJoIjoiMC5BWE1BT0JXLUVkaDVPVW1DdUxkbmdGMkNXd01BQUFBQUFBQUF3QUFBQUFBQUFBQnpBTFUuIiwic2NwIjoiVXNlci5SZWFkIHByb2ZpbGUgb3BlbmlkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImlua25vd25udHdrIiwia21zaSJdLCJzdWIiOiJnVEFZQnluTW9pMlVsdXd5SXNmRmlNRElUYzR1R041U3NyZXpydGtMa01BIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkVVIiwidGlkIjoiMTFiZTE1MzgtNzlkOC00OTM5LTgyYjgtYjc2NzgwNWQ4MjViIiwidW5pcXVlX25hbWUiOiJjaHJrQGFya2l0ZW1hLmNvbSIsInVwbiI6ImNocmtAYXJraXRlbWEuY29tIiwidXRpIjoiLVZ2RXVLMmwxVTZrZXlBTTV6ZFFBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJmRWFfSW9mRzZNa05CcnJ4dGk0VE5MSnBZMzdpdjdkdnhneEVFQ21BOWxFIn0sInhtc190Y2R0IjoxNDMxOTMzMDEzfQ.fwtnwFevjtRjyfg6pSisAjP4keskEDus8_J45MAZIZyyIbJAGCim-vrul7JVnaJo3ZnhlR3Dr-K5IEZzvDTYS5nbWvuCotInrtHe8nb-vWfdf5HGhippdo7qKRYaNSXH1kpXfolgYmZ6J5bOOYa1W0pT5GsIv1Secnf4fzpGtKW7e9axsL0ca4RjB4QKcgXDkOMhfUcykON0ojIrceLm5rRzBU8vPuTj1WEMRWbVK23vCXT-zNWhRUSNJ_Ekn_SswBEYzT4e_IpSu1_XoCAhWKYESxdfZS9VGH_a6if4v7SZJIdn9ukIUnZ5lcSCHDb_d_i9db8NFROa-dShOdozag&publicKey=%7B%0A%20%20%22e%22%3A%20%22AQAB%22%2C%0A%20%20%22kty%22%3A%20%22RSA%22%2C%0A%20%20%22n%22%3A%20%22spvQcXWqYrMcvcqQmfSMYnbUC8U03YctnXyLIBe148OzhBrgdAOmPfMfJi_tUW8L9svVGpk5qG6dN0n669cRHKqU52GnG0tlyYXmzFC1hzHVgQz9ehve4tlJ7uw936XIUOAOxx3X20zdpx7gm4zHx4j2ZBlXskAj6U3adpHQNuwUE6kmngJWR-deWlEigMpRsvUVQ2O5h0-RSq8Wr_x7ud3K6GTtrzARamz9uk2IXatKYdnj5Jrk2jLY6nWt-GtxlA_l9XwIrOl6Sqa_pOGIpS01JKdxKvpBC9VdS8oXB-7P5qLksmv7tq-SbbiOec0cvU7WP7vURv104V4FiI_qoQ%22%0A%7D).

It says it cannot verify the signature.

Yes, the Azure setup should be the same:
![Screenshot from 2022-04-25 10-59-52](https://user-images.githubusercontent.com/16247318/165056446-2d5ebb06-a736-46bd-817e-63fd6cc20ec4.png)
![Screenshot from 2022-04-25 10-57-51](https://user-images.githubusercontent.com/16247318/165056489-7699792b-0471-490a-879b-c5e7703532e8.png)

**Comment by ocni-dtu** [comment]
Yeah, so it turns out that I fucked up 🤦
The mistake was in the React code. Anyways I'm just going to explain below for anyone in the future.

```typescript
// main.tsx

import { MsalProvider } from "@azure/msal-react";
import { msalInstance } from "./features/utils/aad";

ReactDOM.render(
  <React.StrictMode>
    <MsalProvider instance={msalInstance}>
      <App />
    </MsalProvider>
  </React.StrictMode>,
  document.getElementById("root")
);
```

```typescript
// features/utils/aad.tsx

import {
  Configuration,
  RedirectRequest,
  PublicClientApplication,
  EventMessage,
  EventType,
  AuthenticationResult,
} from "@azure/msal-browser";

export const msalConfig: Configuration = {
  auth: {
    clientId: import.meta.env.VITE_AAD_CLIENT_ID as string,
    authority: `https://login.microsoftonline.com/${import.meta.env.VITE_AAD_TENANT_ID}`,
    redirectUri: "http://localhost:3000/login",
  },
  cache: {
    cacheLocation: "sessionStorage", 
    storeAuthStateInCookie: false,
  },
};

export const msalInstance = new PublicClientApplication(msalConfig);

msalInstance.addEventCallback((event: EventMessage) => {
  if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
    const payload = event.payload as AuthenticationResult;
    const account = payload.account;
    msalInstance.setActiveAccount(account);
  }
});

// MSAL.js v2 exposes several account APIs, logic to determine which account to use is the responsibility of the developer
const account = msalInstance.getAllAccounts()[0];

export const accessTokenRequest = {
  scopes: [`api://${import.meta.env.VITE_AAD_APP_CLIENT_ID}/user_impersonation`],
  account: account,
};
```
The issue was that I had my `accessTokenRequest` without the id of the backend app registration

```typescript
export const accessTokenRequest = {
  scopes: [`user_impersonation`],
  account: account,
};
```

**Comment by JonasKs** [comment]
Glad you figured it out, and thanks for providing an example for future reference. 

Have a good week 😊
